### ISSUE TITLE
AtmosphereCoordinator prevents Play Reload in DEV mode

### ISSUE THREAD

**Issue by mickgiles** [Atmosphere/atmosphere-play#16]
When changing a file in DEV mode and Play attempts to recompile/reload AtmosphereCoordinator's static final references prevent the parent ClassLoader from being garbage collected. The result is that objects of the same type created in a different ClassLoader throw ClassCastExceptions on comparisons. e.g. "Cannot cast models.Foo to models.Foo" in a loop like 
for(Foo bar : listOfFoos) {
}

**Comment by jfarcand** [comment]
@mickgiles Apology for the delay. If you have a solution, please do me a favor and do a pull request

**Comment by mickgiles** [comment]
Thanks @jfarcand I have submitted a pull request that resolves this issue
