### ISSUE TITLE
long-polling and jsonp transport produces duplicate messages in sample chat application

### ISSUE THREAD

**Issue by nchorniy** [Atmosphere/atmosphere-play#25]
That happened with 'chat' application from the 'play-samples' folder of
[atmosphere-samples](https://github.com/Atmosphere/atmosphere-samples).

If the transport is changed to **jsonp** or **long-polling** inside index.scala.html, each new text message is received and displayed twice in the browser, although Chat.onMessage() is executed only once on server side. Below is the details of code changes and output from server and client side.

Before:
```javascript
var transport = 'websocket';
```

After:
```javascript
var transport = 'jsonp';
```

![image](https://cloud.githubusercontent.com/assets/778767/6698931/f3b8ceda-cd05-11e4-8071-5909ab79416e.png)

### Output on server side

Chat.onMessage() call was not duplicated

>[info] o.a.s.play.Chat - John just send John
>[info] o.a.s.play.Chat - John just send Test

##### Page loaded:
>Atmosphere: jsonp.window
>atmosphere.js:3220 Atmosphere: Firing onOpen
>atmosphere.js:3220 Atmosphere: Firing onOpen
>atmosphere.js:3220 Atmosphere: jsonp.onload

##### User name selected ("John"):
onMessage method call was duplicated

>Atmosphere: ajaxRequest.onreadystatechange, new state: 2
>atmosphere.js:3220 Atmosphere: ajaxRequest.onreadystatechange, new state: 4
>atmosphere.js:3220 Atmosphere: jsonp.window
>atmosphere.js:1121 Resource interpreted as Script but transferred with MIME type text/plain: "http://localhost:9000/chat?X-Atmosphere-tracking-id=df812c0d-af62-4725-a63a…ication%2Fjson&X-atmo-protocol=true&jsonpTransport=atmosphere1426628629428".
atmosphere.js:3220 Atmosphere: Firing onMessage
atmosphere.js:3220 Atmosphere: Firing onMessage
atmosphere.js:3220 Atmosphere: jsonp.onload
atmosphere.js:1121 Resource interpreted as Script but transferred with MIME type text/plain: "http://localhost:9000/chat?X-Atmosphere-tracking-id=df812c0d-af62-4725-a63a…ication%2Fjson&X-atmo-protocol=true&jsonpTransport=atmosphere1426628629429".
atmosphere.js:3220 Atmosphere: jsonp.window
atmosphere.js:3220 Atmosphere: Firing onMessage
atmosphere.js:3220 Atmosphere: Firing onMessage
atmosphere.js:3220 Atmosphere: jsonp.onload

##### Message sent ("Test"):
onMessage method call was duplicated, in result "Test" message is shown twice.

>Atmosphere: ajaxRequest.onreadystatechange, new state: 2
>atmosphere.js:3220 Atmosphere: ajaxRequest.onreadystatechange, new state: 4
>atmosphere.js:3220 Atmosphere: jsonp.window
>atmosphere.js:3220 Atmosphere: Firing onMessage
>atmosphere.js:1121 Resource interpreted as Script but transferred with MIME type text/plain: "http://localhost:9000/chat?X-Atmosphere-tracking-id=df812c0d-af62-4725-a63a…ication%2Fjson&X-atmo-protocol=true&jsonpTransport=atmosphere1426628629431".
atmosphere.js:3220 Atmosphere: Firing onMessage
atmosphere.js:3220 Atmosphere: jsonp.onload
atmosphere.js:1121 Resource interpreted as Script but transferred with MIME type text/plain: "http://localhost:9000/chat?X-Atmosphere-tracking-id=df812c0d-af62-4725-a63a…ication%2Fjson&X-atmo-protocol=true&jsonpTransport=atmosphere1426628629432".
atmosphere.js:3220 Atmosphere: jsonp.window
atmosphere.js:3220 Atmosphere: Firing onMessage
atmosphere.js:3220 Atmosphere: Firing onMessage
atmosphere.js:3220 Atmosphere: jsonp.onload

##### Page loaded:
>Atmosphere: ajaxRequest.onreadystatechange, new state: 2
atmosphere.js:3220 Atmosphere: ajaxRequest.onreadystatechange, new state: 3
atmosphere.js:3220 Atmosphere: ajaxRequest.onreadystatechange, new state: 4
atmosphere.js:3220 Atmosphere: ajaxRequest.onreadystatechange, new state: 2
atmosphere.js:3220 Atmosphere: Firing onOpen
atmosphere.js:3220 Atmosphere: Firing onOpen
atmosphere.js:3220 Atmosphere: ajaxRequest.onreadystatechange, new state: 3

##### User name selected ("John"):
onMessage method call was duplicated

>Atmosphere: ajaxRequest.onreadystatechange, new state: 2
atmosphere.js:3220 Atmosphere: ajaxRequest.onreadystatechange, new state: 4
atmosphere.js:3220 Atmosphere: ajaxRequest.onreadystatechange, new state: 3
atmosphere.js:3220 Atmosphere: ajaxRequest.onreadystatechange, new state: 4
atmosphere.js:3220 Atmosphere: Firing onMessage
atmosphere.js:3220 Atmosphere: Firing onMessage
atmosphere.js:3220 Atmosphere: ajaxRequest.onreadystatechange, new state: 2
2atmosphere.js:3220 Atmosphere: ajaxRequest.onreadystatechange, new state: 3
atmosphere.js:3220 Atmosphere: ajaxRequest.onreadystatechange, new state: 4
atmosphere.js:3220 Atmosphere: Firing onMessage
atmosphere.js:3220 Atmosphere: Firing onMessage
atmosphere.js:3220 Atmosphere: ajaxRequest.onreadystatechange, new state: 2
atmosphere.js:3220 Atmosphere: ajaxRequest.onreadystatechange, new state: 3

##### Message sent ("Test"):
onMessage method call was duplicated, in result "Test" message is shown twice.

Atmosphere: ajaxRequest.onreadystatechange, new state: 2
>atmosphere.js:3220 Atmosphere: ajaxRequest.onreadystatechange, new state: 4
atmosphere.js:3220 Atmosphere: ajaxRequest.onreadystatechange, new state: 3
atmosphere.js:3220 Atmosphere: ajaxRequest.onreadystatechange, new state: 4
atmosphere.js:3220 Atmosphere: Firing onMessage
atmosphere.js:3220 Atmosphere: Firing onMessage
atmosphere.js:3220 Atmosphere: ajaxRequest.onreadystatechange, new state: 2
2atmosphere.js:3220 Atmosphere: ajaxRequest.onreadystatechange, new state: 3
atmosphere.js:3220 Atmosphere: ajaxRequest.onreadystatechange, new state: 4
atmosphere.js:3220 Atmosphere: Firing onMessage
atmosphere.js:3220 Atmosphere: Firing onMessage
atmosphere.js:3220 Atmosphere: ajaxRequest.onreadystatechange, new state: 2
atmosphere.js:3220 Atmosphere: ajaxRequest.onreadystatechange, new state: 3

Atmosphere-samples **Code Revision**: d792baf19de133a9d8189e276711c60c72246b7e, master

**Note**: this is not an issue in case if transport is changed to 'jsonp' or 'long-polling' in "samples/sse-chat" project.
Browser: Google Chrome 41.0.2272.89 (Windows)

atmosphere-play 2.1.0 was used (build.sbt changed):

```sbt
libraryDependencies += "org.atmosphere" % "atmosphere-play" % "2.1.0"
```

**Comment by jfarcand** [comment]
Same as #24
