### ISSUE TITLE
ajax transport does not work in sample chat application

### ISSUE THREAD

**Issue by nchorniy** [Atmosphere/atmosphere-play#27]
Sample application: play-samples/chat, [atmosphere-samples](https://github.com/Atmosphere/atmosphere-samples).

If the transport is changed to **ajax** inside index.scala.html, server side Chat.onReady() is not called and (therefore), client side does not receive onOpen(response) callback. Chat is not initialized and application stays in 'Connecting' state.

Before
```javascript
var transport = 'websocket';
```

After
```javascript
var transport = 'ajax';
```

### Javascipt output

>The key "target-densitydpi" is not supported.
atmosphere.js:3220 Atmosphere: ajaxRequest.onreadystatechange, new state: 2
atmosphere.js:3220 Atmosphere: ajaxRequest.onreadystatechange, new state: 4

### Server logs output

>[info] o.a.s.play.Chat - null just send disconnecting
[debug] o.a.p.AtmosphereCoordinator - Transport polling resumeOnBroadcast false
[debug] o.a.p.AtmosphereCoordinator - Transport ajax resumeOnBroadcast false
[info] o.a.s.play.Chat - Browser 66ddf330-0aaf-4fcf-b9d1-506bb07fddb4 unexpectedly disconnected
[warn] o.a.c.AtmosphereResponse - AtmosphereResponse for 66ddf330-0aaf-4fcf-b9d1-506bb07fddb4 has been closed

### Notes
* Browser: Google Chrome 41.0.2272.89 (Windows)
* atmosphere-samples revision: master, d792baf19de133a9d8189e276711c60c72246b7e
* atmosphere-play 2.1.0 was used (build.sbt changed):
```sbt
libraryDependencies += "org.atmosphere" % "atmosphere-play" % "2.1.0"
```

**Comment by jfarcand** [comment]
The 'ajax` transport is not really supported as it does the same as `polling`, Better to use `long-polling` instead. Thanks for the report!
