### ISSUE TITLE
Creation of several concurrent SSE connections doesn't work

### ISSUE THREAD

**Issue by nchorniy** [Atmosphere/atmosphere-play#29]
The code of [atmosphere-samples/play-samples/chat](https://github.com/Atmosphere/atmosphere-samples/tree/master/play-samples/chat) was modified to use SSE transport and create 10 chat rooms on single page.

It turns out, that if >5 connections are opened, connections become broken (browser shows some connections in "PENDING" state).

In that state we can't send user name/messages etc - everything stops working.
If # of subscriptions (chats) is reduced to 2 (3 .. up to 5) - it seems to be workable.

Source code of the modified sample: https://www.dropbox.com/s/3bghaxv2o6file2/chat.zip?dl=0

**Comment by jfarcand** [comment]
This is the browser connection limits and not an Atmosphere issue.
