### ISSUE TITLE
Is the dependency on servlet-api 2.5 outdated?

### ISSUE THREAD

**Issue by fdietze** [Atmosphere/atmosphere-play#30]
Hi,

When I'm starting play and request a site, play crashes with
```
java.lang.NoSuchMethodError: javax.servlet.http.HttpServletResponse.getHeader
```

As this method was introduced in servlet-api 3.0 ([javadoc](https://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletResponse.html)), I guess that the dependency on 2.5 is outdated.
I'm using this workaround in my build.sbt dependencies to fix it:
```scala
    "org.atmosphere" % "atmosphere-play" % "2.1.1" exclude("javax.servlet", "servlet-api"),
    "javax.servlet" % "javax.servlet-api" % "3.1.0",
```

It would be nice to see this fixed.

Thank you!

**Comment by jfarcand** [comment]
In 2.1.2+
