### ISSUE TITLE
java.lang.ClassNotFoundException: com.ning.http.multipart.MultipartRequestEntity with Play 2.3.x in combination with wasync 2.1.2

### ISSUE THREAD

**Issue by umbreak** [Atmosphere/atmosphere-play#33]
The issue was first described in wasync but It happens also without the wasync running and atmosphere-play and `async-http-client` as a dependency.

The whole description and stacktrace is in: https://github.com/Atmosphere/wasync/issues/132

**Comment by slandelle** [comment]
You can't use wasync 2.1.2 with Play 2.3 because of conflicting versions of AsyncHttpClient:
* wasync 2.1.2  => AHC 1.9
* Play 2.3 => AHC 1.8

Either upgrade Play to 2.4, or downgrade wasync.

**Comment by umbreak** [comment]
OK. Thanks.
