### ISSUE TITLE
AtmosphereResource.session() is null when a play session exists

### ISSUE THREAD

**Issue by marchaos** [Atmosphere/atmosphere-play#9]
It would be nice if there was some way to access the play session so that we can authenticate the user in onReady()

**Comment by daut-morina** [comment]
Is there any news on this? Still returns null.

**Comment by jfarcand** [comment]
@daut-morina Have you tested the latest version?

**Comment by daut-morina** [comment]
@jfarcand Thanks for your quick reply.

Yes, I'm using 2.1.0 on Play 2.3. Is session support enabled by default or do I have to enable it first like I would have to when using the generic atmosphere framework?

**Comment by daut-morina** [comment]
In the play chat example in Global.java I do following:
```
@Override
public void onStart(Application application) {
    instance().framework().getAtmosphereConfig().setSupportSession(true);
    instance().discover(Chat.class).ready();
}
```  
and now the log shows:
```
[info] o.a.c.AtmosphereFramework - HttpSession supported: true
```

The result is that following:
```
@Ready
public void onReady(final AtmosphereResource r) {
    logger.info("Session: " + r.session());
    logger.info("Session from request: " + r.getRequest().getSession());
    logger.info("Cookie from request: " + r.getRequest().getCookies().length);
}
```
gives you this:
```
[info] o.a.s.play.Chat - Session: org.atmosphere.cpr.AtmosphereRequest$NoOpsRequest$1@6c7c94c3
[info] o.a.s.play.Chat - Session: org.atmosphere.cpr.AtmosphereRequest$NoOpsRequest$1@6c7c94c3
[info] o.a.s.play.Chat - Session: 0
```

**Comment by rafalfaron** [comment]
@daut-morina
pull request I provided above was merged to play-atmoshpere 2+ - it introduces hook in form of AtmospherePlaySessionConverter for play session access from atmosphere parts.

It will not just give you access to full play HTTP session, but rather provides a hook where you can read some values from it and put it as attributes of Atmoshphere request.

(There is no default implementation of AtmospherePlaySessionConverter, you need to prepare any that will work for you and hook it via properties ("org.atmopshere.play.AtmospherePlaySessionConverter" property) - just watch out for problems with them under play development mode ())


See also 
* https://groups.google.com/forum/#!topic/atmosphere-framework/y-IuAm7MT8M
* https://groups.google.com/forum/#!searchin/atmosphere-framework/rafalfaron/atmosphere-framework/Kkr2NjwY-uE/p43F2vMuRQQJ

I use this hook in my projects to access play-authenticate sessions and it works fine.
